### ISSUE TITLE
Test user details

### ISSUE THREAD

**Issue by lukebars** [MSetnik/NotesApp#7]
Hey, any chance of adding test user details to Readme? 

Thanks

**Comment by MSetnik** [comment]
Hi,

Authentication is still work in progress. Notes from firestore are not
displaying yet.
You can register freely with any mail (needs to be mail format and there is
no account verification) and a password.

Login details:
mail: matko.setnik@gmail.com
pw: 123456789


Latest working build published on playstore is in branch google-play-v1.2.1.
https://github.com/MSetnik/NotesApp/tree/google-play-v1.2.1
